name: Build and Release

on:
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create a release draft (true/false)'
        required: false
        default: 'false'

permissions:
  contents: write  # 允许创建 release 和上传资产

env:
  CARGO_TERM_COLOR: always
  # RUSTFLAGS: '-Ctarget-feature=+crt-static'  # Windows only, set globally and filtered by platform

jobs:
  build:
    strategy:
      matrix:
        platform:
          - os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            pdfium_url: https://github.com/bblanchon/pdfium-binaries/releases/latest/download/pdfium-linux-x64.tgz
            pdfium_lib: lib/libpdfium.so
            artifact_name: tex2img-linux-x64
          # - os: macos-latest
          #   target: x86_64-apple-darwin
          #   pdfium_url: https://github.com/bblanchon/pdfium-binaries/releases/latest/download/pdfium-mac-x64.tgz
          #   pdfium_lib: lib/libpdfium.dylib
          #   artifact_name: tex2img-macos-x64
          # - os: macos-latest
          #   target: aarch64-apple-darwin
          #   pdfium_url: https://github.com/bblanchon/pdfium-binaries/releases/latest/download/pdfium-mac-arm64.tgz
          #   pdfium_lib: lib/libpdfium.dylib
          #   artifact_name: tex2img-macos-arm64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            pdfium_url: https://github.com/bblanchon/pdfium-binaries/releases/latest/download/pdfium-win-x64.tgz
            pdfium_lib: bin/pdfium.dll
            artifact_name: tex2img-windows-x64

    runs-on: ${{ matrix.platform.os }}

    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 安装 Rust
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}
      - name : Init Rust
        run: |
          rustup update
          rustup toolchain install stable
          rustup default stable
      # 缓存 Cargo 依赖
      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2.7.8

      # 安装 vcpkg 依赖（Linux）
      - name: Install vcpkg dependencies (Linux)
        if: matrix.platform.os == 'ubuntu-20.04'
        run: |
          sudo apt-get update -qq && \
          sudo apt-get install -y --no-install-recommends \
            build-essential clang lld cmake curl autoconf-archive autoconf automake \
            pkg-config libssl-dev uuid-dev \
            libfontconfig1-dev libharfbuzz-dev \
            libicu-dev zlib1g-dev && \

          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
          echo "RUSTFLAGS=-C linker=clang -C link-arg=-fuse-ld=lld" >> $GITHUB_ENV

          echo "CARGO_PROFILE_RELEASE_LTO=true" >> $GITHUB_ENV
          echo "CARGO_PROFILE_RELEASE_PANIC=abort" >> $GITHUB_ENV

          echo "CXXFLAGS=-fPIC" >> $GITHUB_ENV
          echo "CFLAGS=-fPIC" >> $GITHUB_ENV



      # 安装 vcpkg 依赖（macOS）
      - name: Install vcpkg dependencies (macOS)
        if: contains(matrix.platform.os, 'macos')
        run: |
          brew install pkg-config
          sudo xcode-select --install || true

      # - name: Install MSVC (Windows)
      #   if: matrix.platform.os == 'windows-latest'
      #   uses: ilammy/msvc-dev-cmd@v1

      # 安装 vcpkg
      # - name: Install vcpkg
      #   run: |
      #     git clone https://github.com/microsoft/vcpkg.git ./vcpkg
      #     ./vcpkg/bootstrap-vcpkg.sh -disableMetrics

      # 运行 cargo-vcpkg
      - name: Build vcpkg dependencies
        shell: bash
        run: |
          # 设置不同系统的路径和可执行文件
          if [ "$RUNNER_OS" = "Windows" ]; then
            VCPKG_ROOT="$USERPROFILE\.vcpkg"
            VCPKG_EXE="vcpkg.exe"
          else
            VCPKG_ROOT="${HOME}/.vcpkg"
            VCPKG_EXE="vcpkg"
          fi
          
          # Clone vcpkg
          git clone https://github.com/microsoft/vcpkg.git "$VCPKG_ROOT"
          echo "VCPKG_ROOT=$VCPKG_ROOT" >> $GITHUB_ENV
          
          # Bootstrap vcpkg
          "$VCPKG_ROOT/bootstrap-vcpkg.sh" -disableMetrics
          
          # 安装依赖库
          "$VCPKG_ROOT/$VCPKG_EXE" install fontconfig freetype "harfbuzz[graphite2]" icu
          
          # 安装 cargo-vcpkg
          cargo install cargo-vcpkg
          
          # 构建依赖
          cargo vcpkg build
        # env:
          # CFLAGS: "-D_GNU_SOURCE"

      # 设置环境变量
      - name: Set environment variables
        shell: bash
        run: |
          echo "TECTONIC_PKGCONFIG_FORCE_SEMI_STATIC=1" >> $GITHUB_ENV
          echo "CARGO_PROFILE_RELEASE_PANIC=abort" >> $GITHUB_ENV
          echo "TECTONIC_DEP_BACKEND=vcpkg" >> $GITHUB_ENV


          if ([ "${{ matrix.platform.os }}" == "windows-latest" ]); then
            echo "VCPKGRS_TRIPLET=x64-windows-static-release" >> $GITHUB_ENV
            echo "RUSTFLAGS=-C target-feature=+crt-static" >> $GITHUB_ENV
          fi

          if ([ "${{ matrix.platform.os }}" == "ubuntu-20.04" ]); then
            echo "RUSTFLAGS=-C linker=clang -C link-arg=-fuse-ld=lld" >> $GITHUB_ENV
          fi

      # 编译项目
      - name: Build project
        run: |
          cargo build --release 

      # 下载 pdfium
      - name: Download pdfium
        run: |
          curl -L -o pdfium.tgz "${{ matrix.platform.pdfium_url }}"
          mkdir -p pdfium
          tar -xzf pdfium.tgz -C pdfium

      # 准备产物
      - name: Prepare artifacts
        shell: bash
        run: |
          mkdir -p artifacts
          # 复制可执行文件和库
          if [ "${{ matrix.platform.os }}" == "windows-latest" ]; then
            cp target/release/tex2img.exe artifacts/
            cp target/release/libtex2img.dll artifacts/
          else
            cp target/release/tex2img artifacts/
            cp target/release/liblibtex2img.so artifacts/libtex2img.so
          fi
          # 复制 pdfium 动态库
          cp pdfium/${{ matrix.platform.pdfium_lib }} artifacts/
          # 复制 test_lib.py
          cp test_lib.py artifacts/
          # 创建压缩包
          cd artifacts
          if [ "${{ matrix.platform.os }}" == "windows-latest" ]; then
            zip -r ../${{ matrix.platform.artifact_name }}.zip .
          else
            tar -czf ../${{ matrix.platform.artifact_name }}.tar.gz .
          fi

      # 上传产物
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.artifact_name }}
          path: ${{ matrix.platform.artifact_name }}.*

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.create_release == 'true'
    steps:
      # 检出代码以获取元数据
      - name: Checkout repository
        uses: actions/checkout@v4

      # 下载所有产物
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      # 创建 release draft
      - name: Create release draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME=$(date -u +%Y%m%d%H%M%S)
          gh release create "$TAG_NAME" \
            --draft \
            --title "Release $TAG_NAME" \
            --notes "Automated release for multi-platform build" \
            artifacts/*/*
